[package]
name = "hyper-gpu-prototype"
version = "0.1.0"
edition = "2024"
rust-version = "1.94"
publish = false

[workspace]

[dependencies]
slint = { version = "=1.18.1", default-features = false, features = ["std", "backend-winit", "renderer-software", "accessibility", "compat-1-2"] }

[build-dependencies]
slint-build = "=1.18.1"

[profile.dev]
debug = 0
incremental = false
